apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: parent-child-local-backend
  namespace: ocm-system
spec:
  interval: 1m0s
  componentVersionRef:
    name: parent-child
    namespace: ocm-system
  source:
    sourceRef:
      kind: Snapshot
      name: parent-child-backend-snapshot-deployment
      namespace: ocm-system
  
  snapshotTemplate:
    name: parent-child-backend-deployment-localized
    createFluxSource: true
