apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: parent-child-approach
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: github.com/sidhishruti22/parent-child/frontend-app
    namespace: ocm-system
  resource:
    name: deployment
  snapshotTemplate:
    name: parent-child-frontend-snapshot-deployment
