apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: parent-child-local-frontend
  namespace: ocm-system
spec:
  interval: 1m0s
  componentVersionRef:
    name: parent-child
    namespace: ocm-system
  source:
    sourceRef:
      kind: Snapshot
      name: parent-child-snapshot-deployment
      namespace: ocm-system
  configRef:
    resource:
      resourceRef:
        name: config
  snapshotTemplate:
    name: parent-child-frontend-deployment-localized
    createFluxSource: true
