apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: parent-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: parent-deployment
    namespace: ocm-system
  resource:
    name: deployment
  snapshotTemplate:
    name: parent-deployment
