apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: github.com/sidhishruti22/parent-child/parent-deployment
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: github.com/sidhishruti22/parent-child/parent-deployment
    namespace: ocm-system
  resource:
    name: parent-deployment
  snapshotTemplate:
    name: parent-snapshot-deployment
