apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: parent-child-approach
  namespace: ocm-system
spec:
  interval: 10m0s
  componentVersionRef:
    name: parent-child-approach
    namespace: ocm-system
  resource:
    name: deploymeny
  snapshotTemplate:
    name: parent-child-2-snapshot-deployment
